keypoints_list = [
    "RWRL",
    "RWRM",
    "RELL",
    "RELM",
    "RSHF",
    "RSHB",
    "LWRL",
    "LWRM",
    "LELL",
    "LELM",
    "LSHF",
    "LSHB",
    "RANL",
    "RANM",
    "RKNL",
    "RKNM",
    "RTRO",
    "LANL",
    "LANM",
    "LKNL",
    "LKNM",
    "LTRO",
    "REAR",
    "LEAR",
]

exp_keypoints_list = [
    "LEFT_SHOULDER",
    "RIGHT_SHOULDER",
    "LEFT_ELBOW",
    "RIGHT_ELBOW",
    "LEFT_WRIST",
    "RIGHT_WRIST",
    "LEFT_HIP",
    "RIGHT_HIP",
    "LEFT_KNEE",
    "RIGHT_KNEE",
    "LEFT_ANKLE",
    "RIGHT_ANKLE",
]

keypoints_17 = [
    'NOSE',
    'LEFT_EYE',
    'RIGHT_EYE',
    'LEFT_EAR',
    'RIGHT_EAR',
    'LEFT_SHOULDER',
    'RIGHT_SHOULDER',
    'LEFT_ELBOW',
    'RIGHT_ELBOW',
    'LEFT_WRIST',
    'RIGHT_WRIST',
    'LEFT_HIP',
    'RIGHT_HIP',
    'LEFT_KNEE',
    'RIGHT_KNEE',
    'LEFT_ANKLE',
    'RIGHT_ANKLE'
]

# exp_keypoints_connections = {
#     "SHOULDER": [5, 6],
#     "LEFT_UPPER_ARM": [5, 7],
#     "RIGHT_UPPER_ARM": [6, 8],
#     "LEFT_FORE_ARM": [7, 9],
#     "RIGHT_FORE_ARM": [8, 10],
#     "LEFT_TORSO": [5, 11],
#     "RIGHT_TORSO": [6, 12],
#     "GROIN": [11, 12],
#     "LEFT_THIGH": [11, 13],
#     "RIGHT_THIGH": [12, 14],
#     "LEFT_LOWER_LEG": [13, 15],
#     "RIGHT_LOWER_LEG": [14, 16],
# }

exp_keypoints_connections = {
    "SHOULDER": [0, 1],
    "LEFT_UPPER_ARM": [0, 2],
    "RIGHT_UPPER_ARM": [1, 3],
    "LEFT_FORE_ARM": [2, 4],
    "RIGHT_FORE_ARM": [3, 5],
    "LEFT_TORSO": [0, 6],
    "RIGHT_TORSO": [1, 7],
    "GROIN": [6, 7],
    "LEFT_THIGH": [6, 8],
    "RIGHT_THIGH": [7, 9],
    "LEFT_LOWER_LEG": [8, 10],
    "RIGHT_LOWER_LEG": [9, 11],
}
